-- criar schema temp
CREATE SCHEMA temp;
COMMENT ON SCHEMA temp IS 'Tabelas que são utilizadas temporariamente para armazenar dados das OSCs cadastradas';

-- criar as tabelas do schema temp
CREATE TABLE temp.tb_osc_rais_2011(
	bosc_sq_osc integer NOT NULL,
	dcsc_cd_subclasse numeric(7) NOT NULL,
	dcnj_cd_natureza_juridica numeric(4) NOT NULL,
	dcte_cd_tamanho_estabelecimento numeric(2) NOT NULL,
	rais_qt_vinculo_clt smallint,
	rais_qt_vinculo_ativo smallint,
	rais_qt_vinculo_estatutario smallint,
	rais_in_atividade boolean,
	rais_in_negativa boolean,
	rais_in_osc boolean NOT NULL DEFAULT false,
	CONSTRAINT pk_rais PRIMARY KEY (bosc_sq_osc)
);

CREATE TABLE temp.tb_osc_siconv_2008_2012(
	bosc_sq_osc integer NOT NULL,
	siconv_qt_parceria_finalizada smallint NOT NULL,
	siconv_qt_parceria_execucao smallint NOT NULL,
	siconv_vl_global double precision NOT NULL,
	siconv_vl_repasse double precision NOT NULL,
	siconv_vl_contrapartida_financeira double precision NOT NULL,
	siconv_vl_contrapartida_outras double precision NOT NULL,
	siconv_vl_empenhado double precision NOT NULL,
	siconv_vl_desembolsado double precision NOT NULL,
	CONSTRAINT pk_siconv PRIMARY KEY (bosc_sq_osc)
);

CREATE TABLE temp.tb_osc_siconv_2015_completa(
	nr_convenio text,
	ano_convenio text,
	ano_proposta text,
	nr_proposta text,
	tx_modalidade text,
	tx_situacao text,
	tx_subsituacao text,
	cd_orgao_superior text,
	nm_orgao_superior text,
	cd_orgao_concedente text,
	tx_esfera_adm_proponente text,
	tx_regiao_proponente text,
	uf_proponente text,
	nm_municipio_proponente text,
	cd_identif_proponente text,
	nm_proponente text,
	nm_orgao_concedente text,
	dt_inclusao_proposta text,
	cd_programa text,
	nm_programa text,
	cd_acao_ppa text,
	dt_inicio_vigencia text,
	dt_fim_vigencia text,
	dt_assinatura_convenio text,
	mes_assinatura_convenio text,
	ano_assinatura_convenio text,
	mes_publicacao_convenio text,
	ano_publicacao_convenio text,
	dt_publicacao text,
	dt_ultimo_empenho text,
	dt_ultimo_pgto text,
	vl_global double precision,
	vl_repasse double precision,
	vl_contrapartida_total double precision,
	vl_contrapartida_financ double precision,
	vl_contrapartida_bens_serv double precision,
	vl_desembolsado double precision,
	vl_empenhado double precision,
	tx_objeto_convenio text,
	tx_justificativa text,
	tx_endereco_proponente text,
	tx_bairro_proponente text,
	nr_cep_proponente text,
	nm_respons_proponente text,
	cd_respons_proponente text,
	tx_cargo_respons_proponente text,
	nm_respons_concedente text,
	cd_respons_concedente text,
	tx_cargo_respons_concedente text,
	tx_situacao_publicacao text,
	nr_processo_convenio text,
	nr_interno_convenio text,
	in_assinado_sn text,
	in_aditivo_sn text,
	in_publicado_sn text,
	in_empenhado_sn text,
	in_prorroga_oficio_sn text,
	in_permite_ajuste_cron_fisico text,
	qt_empenhos text,
	qt_aditivos text,
	qt_prorrogas text,
	tx_qualific_proponente text,
	id_convenio text,
	id_prop text,
	id_prop_programa text
);

CREATE TABLE temp.tb_osc_rais_2013_completa(
  id_estab text,
  codemun text,
  uf text,
  regiao_metro text,
  tipo_estab text,
  cnpj_raiz text,
  cei_vinc text,
  subs_ibge text,
  subativ text,
  clas_cnae10 text,
  clas_cnae20 text,
  sbcl_cnae20 text,
  ind_ativ_ano text,
  ind_rais_neg text,
  ind_simples text,
  ind_pat text,
  nat_jur2009 text,
  razao_social text,
  tamestab text,
  qtd_vinc_ativos text,
  qtd_vinc_clt text,
  qtd_vinc_estat text,
  nome_logradouro text,
  num_logradouro text,
  nome_bairro text,
  cep_estab text,
  email_estab text,
  data_abertura text,
  data_baixa text,
  data_encerramento text,
  qtd_port_defic text,
  num_telefone text,
  cnpj_contr_assist text,
  cnpj_contr_assoc text,
  cnpj_contr_conf text,
  cnpj_contr_sindical text,
  vl_contr_assist text,
  vl_contr_assoc text,
  vl_contr_conf text,
  vl_contr_sind text,
  rais_in_osc text,
  dup_id_estabn text,
  dup_id_estab text
);

-- alterar a tabela tb_osc_rais
ALTER TABLE data.tb_osc_rais ALTER COLUMN rais_qt_vinculo_clt TYPE integer;
ALTER TABLE data.tb_osc_rais ALTER COLUMN rais_qt_vinculo_ativo TYPE integer;
ALTER TABLE data.tb_osc_rais ALTER COLUMN rais_qt_vinculo_estatutario TYPE integer;
